{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otail-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: otail.local
      http:
        paths:
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: otail-web
                port:
                  number: 3000
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: otail-server
                port:
                  number: 8080
          - path: /grafana/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 3000
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - otail.local
      secretName: {{ .Release.Name }}-tls
  {{- end }}
{{- end }} 