apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  dsn: {{ printf "http://%s:%s@%s:8123/%s" .Values.clickhouse.auth.username .Values.clickhouse.auth.password .Values.clickhouse.name .Values.clickhouse.auth.database | b64enc }}
  user: {{ .Values.clickhouse.auth.username | b64enc }}
  password: {{ .Values.clickhouse.auth.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  admin-password: {{ .Values.grafana.adminPassword | b64enc }} 