name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server
        ports:
          - 9000:9000
        env:
          CLICKHOUSE_DB: test
          CLICKHOUSE_USER: default
          CLICKHOUSE_PASSWORD: ""

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check for lockfile
        id: check-lockfile
        run: |
          if [ -f "otail-web/pnpm-lock.yaml" ]; then
            echo "lockfile=true" >> $GITHUB_OUTPUT
          else
            echo "lockfile=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          cd otail-web/
          if [ "${{ steps.check-lockfile.outputs.lockfile }}" == "true" ]; then
            pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile
          else
            pnpm install
          fi

      - name: Test backend Go code
        run: |
          cd otail-server
          go mod tidy
          go build -o main .
          go test ./...

      - name: Run unit tests
        run: pnpm exec jest --passWithNoTests
        working-directory: otail-web/

      - name: Run E2E tests
        run: pnpm test:e2e
        working-directory: otail-web/