name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: clickhouse/clickhouse-server
        ports:
          - 9000:9000
        env:
          CLICKHOUSE_DB: test
          CLICKHOUSE_USER: default
          CLICKHOUSE_PASSWORD: ""

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: otail-web/

      - name: Run E2E tests
        run: pnpm test:e2e
        working-directory: otail-web/